[tool.poetry]
name = "conferencias"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
<<<<<<< Updated upstream
python = "^3.10"
sqlmodel = "^0.0.8"
loguru = "^0.7.2"
python-decouple = "^3.8"
python-multipart = "^0.0.6"
h2o-wave = "^1.1.2"
=======
python = "^3.10.4"
h2o-wave = "^1.1.2"
sqlmodel = "^0.0.16"
>>>>>>> Stashed changes

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
<<<<<<< Updated upstream

[tool.taskipy.tasks]
test = "poetry run pytest --cov"
run = "uvicorn inscricoes.main:app --reload --port 8000"
=======
>>>>>>> Stashed changes
